"""Adapters implement model behavior; the runtime owns public transport."""

from typing import Any, Hashable, Protocol, Sequence, runtime_checkable

from .contracts import ServiceDescriptor


class ModelAdapter(Protocol):
    @property
    def descriptor(self) -> ServiceDescriptor: ...
    def load(self) -> None: ...
    def infer(self, request: dict[str, Any]) -> dict[str, Any]: ...
    def close(self) -> None: ...


@runtime_checkable
class BatchModelAdapter(ModelAdapter, Protocol):
    def batch_key(self, request: dict[str, Any]) -> Hashable: ...
    def infer_batch(self, requests: Sequence[dict[str, Any]]) -> Sequence[dict[str, Any]]: ...


class RemoteModelAdapter(Protocol):
    """Async adapter for an existing backend, such as OpenPI's own websocket."""
    @property
    def descriptor(self) -> ServiceDescriptor: ...
    async def load(self) -> None: ...
    async def check(self) -> None: ...
    async def infer(self, request: dict[str, Any]) -> dict[str, Any]: ...
    async def close(self) -> None: ...
